 
data2b<-read.csv("xxxxx.csv")

head(data2b)


install.packages("forecast")
library(forecast)




#create timesearies dataframe
#periodtrain<-ts(data2b$Actual.Gross_sales,start=min(data2b$datetm),end=(max(data2b$datetm)))
perioddata<-ts(data2b$Actual.Gross_sales,frequency=365,start=2011)
periodtrain<-window(perioddata,end=2013.999)
periodtest<-window(perioddata,start=2014.000)
plot(periodtrain,main="Daily Revenue Plot",xlab="",ylab="Revenue")

#Check of autocorrelation and seasonality
lag.plot(periodtrain, lags=9, do.lines=FALSE)
 
#check acf and pacf graph for seasonality check
acf(periodtrain)
pacf(periodtrain)





#Weekly seasonality
periodtrainweek<-ts(data2b$Actual.Gross_sales,freq=7,start=01)
periodtrainweekw<-window(periodtrainweek,end=04)
plot(periodtrainweekw)


acf(periodtrainweekw)



#Some simple methods of forecasting

modelfit1 <- meanf(periodtrain,h=365)
modelfit2 <- naive(periodtrain,h=365)
#modelfit3 <- snaive(periodtrain,h=365)#
 
plot(modelfit1, plot.conf=FALSE,main="Forecasts for revenue with simple timeseries forecasting methods")
lines(modelfit2$mean,col=2)
lines(modelfit3$mean,col=3)
lines(periodtest,col=24)
legend("topright", lty=1, col=c(4,2,3,24),
       legend=c("Mean method","Naive method","Seasonal naive method", "test data"))


accuracy(modelfit1)
accuracy(modelfit2)
accuracy(modelfit3)

 

 
#STL Decomposition method
fit <- stl(ts(periodtrain,frequency=365), t.window=7, s.window="periodic", robust=TRUE)
plot(fit)
eeadj <- seasadj(fit)
plot(naive(eeadj), xlab="index",main="Naive forecasts of seasonally adjusted data")
lines(fitted(fit))


summary(fit)

#using Forecast for STL Decomp
stlforecast<-forecast(fit,method="naive")
plot(stlforecast)


accuracy(stlforecast)



 





#ETS - Exponential Time Series - Holt Winter Method 


#Simple Exponential method - No Trend No Seasonality
fit1 <- ses(periodtrain,h=365)
#Holt Linear - Allow Trend (constant)
fit2 <- holt(periodtrain,h=365)
#Holt Exponential - Trend is exponential in nature
fit3 <- holt(periodtrain,exponential=TRUE,h=365)
#Holt Trend Damped method - Additive Damped
fit4 <- holt(periodtrain,damped=TRUE,h=365)
The forecasts generated by Holt's linear method display a constant trend (increasing or decreasing) indefinitely into the future. Even more extreme are the forecasts generated by the exponential trend method which include exponential growth or decline.

Empirical evidence indicates that these methods tend to over-forecast, especially for longer forecast horizons. Motivated by this observation, Gardner and McKenzie (1985) introduced a parameter that "dampens" the trend to a flat line some time in the future. Methods that include a damped trend have proven to be very successful and are arguably the most popular individual methods when forecasts are required automatically for many series.
fit5 <- holt(periodtrain,exponential=TRUE,damped=TRUE,h=365)






plot(fit3, ylab="Livestock, sheep in Asia (millions)", 
     flwd=1, plot.conf=FALSE)
lines(window(periodtrain,start=2013.005))
lines(fit1$mean,col=2)
lines(fit2$mean,col=3)
lines(fit4$mean,col=5)
lines(fit5$mean,col=6)
lines(periodtest,col=24)
legend("topleft", lty=1, pch=1, col=c(1,2,3,4,5,6,24),
       c("Data","SES","Holt's","Exponential",
         "Additive Damped","Multiplicative Damped"))






#Automated forecasting

fitauto<-forecast(periodtrain,h=365)
plot(fitauto)
accuracy(fitauto)





